version: '3.2'
services:
  nginx:
    container_name: ${PROJECT_NAME}-nginx
    build:
      context: docker/nginx
      args:
        - SERVER_NAME=${NGINX_SERVER_NAME}
        - TZ=${TIMEZONE}
    volumes:
      - ${APP_CODE_PATH}:/var/www/html
      - ${NGINX_HOST_LOG_PATH}:/var/log/nginx
    #      - ${NGINX_SSL_PATH}:/etc/nginx/ssl
    ports:
      - ${NGINX_HOST_HTTP_PORT}:80
    #      - ${NGINX_HOST_HTTPS_PORT}:443
    restart: always
    links:
      - php-fpm
  php-fpm:
    container_name: ${PROJECT_NAME}-php-fpm
    build:
      context: docker/php-fpm
      args:
        - TZ=${TIMEZONE}
    volumes:
      - ${APP_CODE_PATH}:/var/www/html
    restart: always
  php-cli:
    container_name: ${PROJECT_NAME}-php-cli
    build:
      context: docker/php-cli
      args:
        - TZ=${TIMEZONE}
    volumes:
      - ${APP_CODE_PATH}:/var/www/html
    restart: always
    tty: true
  mysql:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASSWORD}
    ports:
      - ${DB_PORT}:3306
